<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <!-- ApplicationIcon>Assets\icon.ico</ApplicationIcon -->
    <AssemblyName>L9HLL.Launcher</AssemblyName>
    <RootNamespace>L9HLL.Launcher</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiscordRichPresence" Version="1.2.1.24" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\L9_Logo_small.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Config\servers.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>